### PR TITLE
Make coding style consistent

### PR DESCRIPTION
**Pull request by dschuermann**
The coding style in this project is mixed. This pull request fixes this:
* always tabs instead of spaces
* no empty lines with indention
* consistent if statements (only if statement for sanity checks are without brackets)
* Remove redundant author tags (author is already in the license header)

### CODE REVIEW

**Comment by klali** [comment]
This doesn't build for me (or on travis-ci).. does it for you and I'm missing something?

**Comment by dschuermann** [comment]
Sry, had a late night typo in it :)

**Comment by dschuermann** [comment]
Any update on  this?

**Comment by klali** [comment]
Sorry, forgotten about it. I'll be merging it today.

**Pull request merged**
